name: scoring_pad
authors:
  - Pascal WILS

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5
  go_router: ^13.0.0
  intl: ^0.19.0
  talker: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pref: ^2.8.0
  flutter_material_color_picker: ^1.2.0
  dropdown_button2: ^2.3.9
  freezed_annotation: ^2.4.1
  fl_chart: ^0.68.0
  share_screenshot_widget: ^0.0.5
  about: ^2.1.3
  flutter_markdown: ^0.6.0
  contextualactionbar: ^3.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  test: ^1.24.9
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  pubspec_extract: ^2.0.5

flutter_launcher_icons:
  android: true
  image_path: "dev_assets/launcher_icon.png"
  adaptive_icon_foreground: "dev_assets/adaptive_launcher_icon.png"
  adaptive_icon_background: "#DBDBDB"
  macos:
      generate: true
      image_path: "dev_assets/launcher_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/game-icons/
    - assets/rules/
    - README.md
    - README.fr.md
